<?php

/**
 * @file
 * Contains review_questions.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function review_questions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the review_questions module.
    case 'help.page.review_questions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds functionality that allows the user to add review questions via a field collection on a per node basis.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_entity_view_alter().
 */
function review_questions_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Check if entity type is node.
  if ($entity->getEntityTypeId() == 'node') {
    // Only show if field_review_questions is displayed.
    if ($display->getComponent('field_review_questions')) {
      // Get enabled node types from config.
      $config = Drupal::config('review_questions.settings');
      $enabled_types = $config->get('node_types');
      if (!empty($enabled_types)) {
        $enabled_types = array_filter($enabled_types);
        // Check if bundle is one of the enabled types for review questions.
        if (in_array($entity->bundle(), $enabled_types)) {
          $current_user = Drupal::currentUser();
          // Show only for authenticated users.
          if ($current_user->id()) {
            // Remove default render array.
            $build['field_review_questions'] = [];
            // Check if field_review_questions has values.
            if ($entity->field_review_questions->getValue()) {
              // Get Review Questions and Answers form.
              $form = Drupal::formBuilder()
                ->getForm('\Drupal\review_questions\Form\ReviewQuestionsAnswersForm', $entity);
              $build['field_review_questions'] = $form;
            }
          }
          else {
            // Hide form for anonymous users.
            $build['field_review_questions']['#access'] = FALSE;
          }
        }
      }
    }
  }
}

/**
 * Implements hook_mail().
 */
function review_questions_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  switch ($key) {
    case 'answers_notification':
      // Get from email address from site config.
      $message['from'] = Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Answers submitted for : @title', ['@title' => $params['node_title']], $options);
      $message['body'][] = Html::escape($params['message']);
      // Add headers to support html emails.
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      break;
  }
}

/**
 * Implements hook_theme().
 */
function review_questions_theme($existing, $type, $theme, $path) {
  return [
    'review_questions_mail' => [
      'variables' => ['review_questions' => NULL],
    ],
  ];
}

/**
 * Prepares variables for answers mail templates.
 *
 * Default template: review-questions-mail.html.twig.
 *
 * @param array $variables
 *   An associative array containing the following keys:
 *   - questions: Array containing questions and answers.
 *   - user: User object who submitted answers.
 *   - node: Node entity to which question belongs.
 */
function template_preprocess_review_questions_mail(&$variables) {
  $review_questions = $variables['review_questions'];
  if ($review_questions['user']) {
    $account = $review_questions['user'];
    $variables['user_name'] = $account->getDisplayName();
    $variables['user_email'] = $account->getEmail();
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function review_questions_paragraph_update(EntityInterface $entity) {
  // Review questions paragraph type.
  if ($entity->bundle() == 'review_questions') {
    if (!empty($entity->field_question->value)) {
      // Fetch paragraph's node entity.
      $node = $entity->getParentEntity();
      $answers_storage = Drupal::entityTypeManager()->getStorage('answers');
      // Fetch answers entity by nid and paragraph id.
      $answers = $answers_storage->loadByProperties([
        'entity_id' => $node->id(),
        'fc_entity_id' => $entity->id(),
      ]);
      if (!empty($answers)) {
        $answer = reset($answers);
        // If question text changed in paragraph, update related answers entity.
        if ($entity->field_question->value != $answer->question->value) {
          //  Update question text.
          $answer->question->value = $entity->field_question->value;
          $answer->save();
        }
      }
    }
  }
}


/**
 * Implements hook_entity_delete().
 */
function review_questions_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  // Delete answers entites when review_questions paragraphs are deleted.
  if ($entity->getEntityTypeId() == 'paragraph' && $entity->bundle() == 'review_questions') {
    if (!empty($entity->field_question->value)) {
      $answers_storage = Drupal::entityTypeManager()->getStorage('answers');
      // Get answers entity related to review_questions paragraph.
      $answers = $answers_storage->loadByProperties([
        'fc_entity_id' => $entity->id(),
      ]);
      if (!empty($answers)) {
        $answer = reset($answers);
        // Delete answers entity.
        $answer->delete();
      }
    }
  }

  // Delete review_questions paragraphs and related answer entities.
  if ($entity->getEntityTypeId() == 'node') {
    // Get enabled node types for reviews_questions from the config.
    $config = Drupal::config('review_questions.settings');
    $enabled_types = $config->get('node_types');
    if (!empty($enabled_types)) {
      $enabled_types = array_filter($enabled_types);
      // Check if bundle is one of the enabled types for review questions.
      if (in_array($entity->bundle(), $enabled_types)) {
        // Paragraph storage.
        $paragraph_storage = Drupal::entityTypeManager()
          ->getStorage('paragraph');
        // Get all review_questions paragraph.
        $paragraphs = $paragraph_storage->loadByProperties([
          'parent_id' => $entity->id(),
          'parent_type' => 'node',
          'type' => 'review_questions',
        ]);
        if (!empty($paragraphs)) {
          // Delete review_questions paragraphs.
          $paragraph_storage->delete($paragraphs);
        }
        // Answers entity storage.
        $answers_storage = Drupal::entityTypeManager()->getStorage('answers');
        // Get all answers entities related to the node.
        $answers = $answers_storage->loadByProperties([
          'entity_id' => $entity->id(),
        ]);
        if (!empty($answers)) {
          // Delete related answer entities.
          $answers_storage->delete($answers);
        }
      }
    }
  }
}
